FROM ghcr.io/actions/actions-runner:latest

RUN sudo apt update -y \
  && sudo apt install npm -y \
  && sudo npm install -g yarn \
  && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install git-lfs libxcomposite-dev libcairo2-dev libjpeg-dev libgif-dev \
  && sudo apt install curl wget libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libxtst6 xorg xauth xvfb libpq-dev -y \
  && sudo rm -rf /var/lib/apt/lists/*

ARG VERSION=v4.44.2
ARG BINARY=yq_linux_amd64
RUN sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
  sudo chmod +x /usr/bin/yq

RUN curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh \
  && sudo apt purge libnode-dev libnode72:amd64 -y \
  && sudo bash /tmp/nodesource_setup.sh \
  && sudo apt install nodejs -y \
  && sudo rm /tmp/nodesource_setup.sh
